version: '2.1'
services:
     elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
       container_name: elasticsearch
       environment:
        ['cluster.name=tr-es-cluster']
       ports:
        - "9500:9200"
        - "9300:9300"
        
       networks:
           docker-elk:

     kibana:
       image: docker.elastic.co/kibana/kibana:6.2.1
       container_name: kibana
       ports:
        - "5601:5601"
       environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9500"
       networks:
          - docker-elk
       depends_on:
          - elasticsearch

networks:
  docker-elk:
    driver: bridge