version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper-local
    ports:
      - "2181:2181"
  kafka:
    build: .
    hostname: kafka-local
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-local
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-local:9092'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
